export const ARTICLES_FROM_INITIAL_VALUES = {
  title: "",
  date: "",
  author: "",
  category: "",
  status: "",
};

export const ARTICLE_DETAILS = [
  {
    id: 1,
    title: "Welcome to Scribble",
    date: "October 9th,2022",
    author: "Oliver Smith",
    category: "Getting Started",
    status: "Draft",
  },
  {
    id: 2,
    title: "Welcome to Neeto",
    date: "October 9th,2022",
    author: "Oliver Smith",
    category: "Misc",
    status: "Published",
  },
  {
    id: 3,
    title: "Setting Up",
    date: "October 9th,2022",
    author: "Oliver Smith",
    category: "Security & Privacy",
    status: "Draft",
  },
  {
    id: 4,
    title: "Writing an article",
    date: "October 9th,2022",
    author: "Oliver Smith",
    category: "Misc",
    status: "Published",
  },
  {
    id: 5,
    title: "Redirections",
    date: "October 9th,2022",
    author: "Oliver Smith",
    category: "Getting Started",
    status: "Draft",
  },
  {
    id: 6,
    title: "301 and 302 redirections",
    date: "October 9th,2022",
    author: "Oliver Smith",
    category: "Security & Privacy",
    status: "Published",
  },
  {
    id: 7,
    title: "Typography",
    date: "October 9th,2022",
    author: "Oliver Smith",
    category: "Misc",
    status: "Draft",
  },
  {
    id: 7,
    title: "Password Protection",
    date: "October 9th,2022",
    author: "Oliver Smith",
    category: "Getting Started",
    status: "Published",
  },
];
