default: &default
  redis_url: <%= ENV['REDISTOGO_URL'] || ENV['REDIS_URL'] || 'redis://localhost:6379/1' %>

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
